apiVersion: v1
kind: Service
metadata:
  name: {{ template "syncthing-relay.fullname" . }}
  labels:
    app: {{ template "syncthing-relay.name" . }}
    chart: {{ template "syncthing-relay.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.relay.port }}
      targetPort: relay
      protocol: TCP
      name: relay
    - port: {{ .Values.service.status.port }}
      targetPort: status
      protocol: TCP
      name: status
  selector:
    app: {{ template "syncthing-relay.name" . }}
    release: {{ .Release.Name }}
